# Whether this GitHub repo is engineering related
engineering_project: true
# Name of the repository/project in English
english_name: Creative Commons Site Reliability Engineering WordPress Data Pull
# All technologies used
technologies: Bash, WordPress
# Whether this repository should be featured on the CC Open Source site
featured: false
